//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDSales_Management_System
{


    public partial class RDSales_Edit_Target
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox txt_asm;
        protected global::System.Web.UI.WebControls.TextBox txt_region;
        protected global::System.Web.UI.WebControls.TextBox txt_DayNo;
        protected global::System.Web.UI.WebControls.TextBox txtTotalPC;
        protected global::System.Web.UI.WebControls.Label lblRegion;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Calendar clDate;
        protected global::System.Web.UI.WebControls.DropDownList cmbTerritories;
        protected global::System.Web.UI.WebControls.GridView dvRDSales;
        protected global::System.Web.UI.WebControls.GridView dgvRegionSummary;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.Button btnView;
        protected global::System.Web.UI.WebControls.Button btnConfirm;
        protected global::System.Web.UI.WebControls.TextBox TextBox3;
        protected global::System.Web.UI.WebControls.Calendar clnDate;


    }
}
